# -*- coding: utf-8 -*-
"""stock_horas_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQhsSbOQ265pNjZ7aHc--HqA2qDb_gfb
"""

from datetime import datetime
import gspread
import streamlit as st

# Conectamos con Google Sheets usando los secrets de Streamlit Cloud
credenciales_dict = dict(st.secrets["gcp_service_account"])
gc = gspread.service_account_from_dict(credenciales_dict)

sh = gc.open("Control Horas")  # El nombre exacto de tu hoja en Drive
worksheet = sh.get_worksheet(0)


def obtener_datos_hoja():
  registros = worksheet.get_all_records()
  diccionario_registros = {}
  for fila in registros:
    fecha = str(fila["Fecha"])
    horas = float(fila["Horas"])
    diccionario_registros[fecha] = horas
  return diccionario_registros


def mostrar_horas_totales(diccionario_registros):
  total_horas_trabajadas = sum(diccionario_registros.values())
  horas_enteras = int(total_horas_trabajadas)
  minutos_restantes = round((total_horas_trabajadas - horas_enteras) * 60)

  st.write(
      f" **Total horas trabajadas:** {horas_enteras} horas y"
      f" {minutos_restantes} minutos"
  )


st.title("Stock Horas de Trabajo")
hoy = datetime.now().strftime("%d-%m-%Y")

registros_actuales = obtener_datos_hoja()
mostrar_horas_totales(registros_actuales)
st.markdown("---")

input_fecha = st.text_input("Fecha (DD-MM-YYYY):", value=hoy)
input_horas = st.number_input("Horas enteras:", min_value=0, value=8, step=1)
input_minutos = st.number_input(
    "Minutos extra:", min_value=0, max_value=59, value=0, step=1
)

if st.button("Guardar en Google Drive", type="primary"):
  horas_decimales = round(input_horas + (input_minutos / 60), 2)
  fec = input_fecha.strip()

  try:
    cell = worksheet.find(fec)
    worksheet.update_cell(cell.row, 2, horas_decimales)
    st.success(f"actualizao. El día {fec} ahora tiene {horas_decimales} horas.")
  except gspread.exceptions.CellNotFound:
    worksheet.append_row([fec, horas_decimales])
    st.success(f"guardao. El día {fec} se ha registrado con {horas_decimales} horas.")

  registros_actuales = obtener_datos_hoja()
  mostrar_horas_totales(registros_actuales)