# -*- coding: utf-8 -*-
"""stock_horas_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQhsSbOQ265pNjZ7aHc--HqA2qDb_gfb
"""

from datetime import datetime
import gspread
import streamlit as st

# Conectamos con Google Sheets usando los secrets de Streamlit Cloud
credenciales_dict = dict(st.secrets["gcp_service_account"])
gc = gspread.service_account_from_dict(credenciales_dict)

sh = gc.open_by_url(
    "https://docs.google.com/spreadsheets/d/1FuKT6RSIbmgQlr7LdSiYBHkuMguhfN4Yd_8OPsdCt6E/edit?gid=0#gid=0"
)
worksheet = sh.get_worksheet(0)


def obtener_datos_hoja():
  registros = worksheet.get_all_records()
  diccionario_registros = {}
  for fila in registros:
    fecha = str(fila.get("Fecha", "")).strip()
    if not fecha:
      continue  # Si la fila no tiene fecha, la ignoramos

    raw_horas = fila.get("Horas", 0)
    try:
      # Si la celda está vacía o no es un número válido, ponemos 0.0
      horas = float(raw_horas) if str(raw_horas).strip() != "" else 0.0
    except ValueError:
      horas = 0.0

    diccionario_registros[fecha] = horas
  return diccionario_registros


def mostrar_horas_totales(diccionario_registros):
  total_horas_trabajadas = sum(diccionario_registros.values())
  horas_enteras = int(total_horas_trabajadas)
  minutos_restantes = round((total_horas_trabajadas - horas_enteras) * 60)

  st.write(
      f" **Total horas trabajadas:** {horas_enteras} horas y"
      f" {minutos_restantes} minutos"
  )


st.title("Stock Horas de Trabajo")
hoy = datetime.now().strftime("%d-%m-%Y")

registros_actuales = obtener_datos_hoja()
mostrar_horas_totales(registros_actuales)
st.markdown("---")

input_fecha = st.text_input("Fecha (DD-MM-YYYY):", value=hoy)
input_horas = st.number_input("Horas enteras:", min_value=0, value=8, step=1)
input_minutos = st.number_input(
    "Minutos extra:", min_value=0, max_value=59, value=0, step=1
)

if st.button("Guardar en Google Drive", type="primary"):
  horas_decimales = round(input_horas + (input_minutos / 60), 2)
  fec = input_fecha.strip()

  # Obtenemos todas las fechas actuales de la columna A
  try:
    # Columna 1 es 'Fecha'
    lista_fechas = worksheet.col_values(1)
  except Exception:
    lista_fechas = []

  # Comprobamos si la fecha ya está en la lista (ignorando la cabecera en la posición 0)
  if fec in lista_fechas[1:]:
    # Buscamos el número de fila exacto (sumamos 1 porque list.index empieza en 0 y la cabecera cuenta)
    fila_idx = lista_fechas[1:].index(fec) + 2
    # Actualizamos la columna 2 (Horas) de esa fila
    worksheet.update_cell(fila_idx, 2, horas_decimales)
    st.success(
        f"¡Actualizado correctamente! El día {fec} ahora tiene {horas_decimales}"
        " horas."
    )
  else:
    # Si no existe, añadimos una fila nueva al final
    worksheet.append_row([fec, horas_decimales])
    st.success(
        f"¡Guardado como nuevo registro! El día {fec} tiene {horas_decimales}"
        " horas."
    )

  st.rerun()
